sudo: true

language:
  - node_js
  - objective-c ## to fix hdiutil required by osx build

os:
  - linux
  - osx

node_js:
  ##- 7
  - 6

cache:
  directories:
    - node_modules

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable npm cache
#
# cache:
#   directories:
#   - $HOME/.yarn-cache

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:jonathonf/wine -y ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -q --fix-missing ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install wine-stable winetricks -y ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export WINEARCH=win32 ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then winecfg ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install winetricks ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-4.8" ; fi
  - npm install -g npm@latest
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 ; fi

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable npm cache
#
# install:
#   - export CXX="g++-4.8"
#   - npm install -g yarnpkg
#   - yarn
#   - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start || true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3 ; fi


script:
  - npm run lint
  #- npm run test
  - npm run build
  - npm run test-e2e
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run package-linux ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run package-win ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package-osx ; fi
