sudo: true
dist: trusty

language:
  - node_js
  - objective-c ## to fix hdiutil required by osx build

os:
  - linux
  - osx

node_js:
  - 7

cache:
  directories:
    - node_modules

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable yarn cache
#
# cache:
#   directories:
#   - $HOME/.yarn-cache

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - sourceline: 'ppa:ubuntu-wine/ppa'
     - sourceline: 'deb http://download.mono-project.com/repo/ubuntu trusty main'
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - xz-utils
      - xorriso
      - wine1.8
      - mono-devel
      - ca-certificates-mono

before_install:
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg --add-architecture i386 ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export WINEARCH=win32 ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then winecfg ; fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="g++-4.8" ; fi
  - yarn install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 ; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start || true ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sleep 3 ; fi


script:

  - yarn run lint
  #- yarn run test
  #- yarn run test-e2e
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run package-linux ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run package-win ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run package-macos ; fi
