sudo: true

language: node_js

os:
  - linux
  - osx

node_js:
  ##- 7
  - 6

cache:
  directories:
    - node_modules

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable npm cache
#
# cache:
#   directories:
#   - $HOME/.yarn-cache

addons:
  apt:
    sources:
      if [[ $TRAVIS_OS_NAME == "linux" ]]; then ubuntu-toolchain-r-test; fi
    packages:
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        - g++-4.8
        - icnsutils
        - graphicsmagick
        - xz-utils
        - xorriso
      ; fi
before_install:
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     - sudo add-apt-repository ppa:wine/wine-builds -y
     - sudo apt-get update -q
     - sudo apt-get install winehq-devel -y
     - export WINEARCH=win32
     - winecfg
     - sudo apt-get install winetricks
  ; fi

install:
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    - export CXX="g++-4.8"
  ; fi
  - npm install -g npm@latest
  - npm install
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  ; fi

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable npm cache
#
# install:
#   - export CXX="g++-4.8"
#   - npm install -g yarnpkg
#   - yarn
#   - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3


script:
  - npm run lint
  #- npm run test
  - npm run build
  - npm run test-e2e
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      npm run package-all
    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      npm run package-osx
    ; fi
